name: 'Code Checks'

on: 'pull_request'

permissions:
  contents: 'read'

jobs:
  phpcs:
    name: 'Code Checks'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.4'
      - run: 'composer install --no-interaction --prefer-dist'
      - run: 'composer phpcs'
