on:
  push:
    tags:
      - 'v*.*.*'

name: 'Release'

jobs:
  build:
    name: 'Create Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
      - name: 'Build package'
        run: |
          {
            echo 'CHANGES<<EOF'
            ./build -gh
            echo EOF
          } >> "$GITHUB_ENV"
      - name: 'Create Draft Release'
        id: 'create_release'
        uses: 'softprops/action-gh-release@v2'
        if: "startsWith(github.ref, 'refs/tags/')"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: '${{ github.ref_name }}'
          name: 'RCG Forest ${{ github.ref_name }}'
          files: 'rcg-forest.zip'
          body: |
            ${{ env.CHANGES }}
          draft: true
          prerelease: false
